-- 1. Create the table for storing detections
create table detections (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  domain text not null,
  tech_name text not null,
  category text,
  url text -- Optional: specific page URL where it was found
);

-- 2. Enable Row Level Security (RLS)
-- This is critical. It locks the table so no one can access it by default.
alter table detections enable row level security;

-- 3. Create a "Write Only" Policy
-- "anon" role (the public API key) can INSERT rows.
-- true means "everyone with the key can insert"
create policy "Allow Anonymous Insert"
on detections
for insert
to anon
with check (true);

-- 4. Create a "Read None" Policy (Implicit)
-- By NOT creating a SELECT policy for the 'anon' role,
-- the API effectively replies with "401 Unauthorized" or empty lists
-- if someone tries to read the data using the public key.
-- ONLY you (via the Supabase Dashboard or Service Role Key) can read the data.

-- 5. Optional: Data Validation (Constraint)
-- Ensure domain isn't empty
alter table detections
add constraint domain_length_check check (char_length(domain) > 0);

-- OPTIONAL: Indexes for faster analytics later
create index idx_detections_domain on detections(domain);
create index idx_detections_tech on detections(tech_name);
